# Generated by Django 3.2.8 on 2021-10-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='value',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
