# Generated by Django 3.2.8 on 2021-10-27 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_likes_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='value',
        ),
        migrations.AlterField(
            model_name='likes',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
