# Generated by Django 3.2.8 on 2021-10-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default=' ', max_length=850),
        ),
    ]
